language: cpp

branches:
  only:
    - master

os:
  - linux

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - lrelease res/lang/en.ts
  - qmake apkstudio.pro CONFIG+=release
  - make

  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage

  - mkdir apkstudio-latest-release
  - cd apkstudio-latest-release
  - cp ../apkstudio ../external/apkstudio.* .

  - ../linuxdeployqt*.AppImage apkstudio.desktop -bundle-non-qt-libs -no-translations -verbose=2 -no-copy-copyright-files -appimage

after_script:
 - curl --upload-file ./*.AppImage https://transfer.sh/apkstudio-$(git rev-parse --short HEAD)-linux_x86_64.AppImage