branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  - lrelease res\lang\en.ts
  - qmake apkstudio.pro
  - mingw32-make

after_build:
  - windeployqt release/apkstudio.exe --release --no-translations
  - rm release/*.o
  - rm release/*.cpp
  - rm release/*.h
  - tree

artifacts:
  - path: release
    type: zip
    name: apkstudio